### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ElRocaYT** [ESX-Org/esx_phone#16]
When you send an emergency alert or call a taxi it would be good to add feedback to know someone received that message, because you don't know if wait for arrival or leave because no one is in duty.

**Comment by RomainLanz** [comment]
Hey @ElRocaYT ! 👋 

You can send a direct reply by clicking below the :pushpin:.
Concerning the feedback that should be send when accepting a call, I think it's not a good idea.

The player should send a message back to the person calling it.

**Comment by ElRocaYT** [comment]
@RomainLanz Yes we do that, when someone call me for a repair I text him back, but I'm used to get feedback automatically from N3MTV framework.

**Comment by jcollins012** [comment]
how would i add an additional icon to the phone? is that possible?

**Comment by ElPumpo** [comment]
You can message back people who text services. @jcollins012 use the trigger available

**Comment by zay7sev** [comment]
Actually it would be nice to have an option in config to have a such feedback since if you receive calls from 10 people in the same time you can't message all of them back otherwise you'll waste time to open them one by one and write a message... if you work as a police or EMS you waste precious time to answer..
